spring:
  datasource:
            username: root
            password: xxxxxxxxx  #自己设置
            url: jdbc:mysql://x.x.x.x:3306/springboot_cache #自己设置
            driver-class-name: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
  jmx:
    enabled: false
  thymeleaf:
    cache: false
  http:
    multipart:
      max-file-size: 10MB
      maxRequestSize : 10MB
  redis:
    host: x.x.x.x        #自己设置

#   数据源其他配置
initialSize: 5
minIdle: 5
maxActive: 20
maxWait: 60000
timeBetweenEvictionRunsMillis: 60000
minEvictableIdleTimeMillis: 300000
validationQuery: SELECT 1 FROM DUAL
testWhileIdle: true
testOnBorrow: false
testOnReturn: false
poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
filters: stat,wall,log4j
maxPoolPreparedStatementPerConnectionSize: 20
useGlobalDataSourceStat: true
connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
logging:
  level:
   com.wjw.springboot.mapper: debug

